// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATM_PB6viTMNV_BmrwkL8p9NGvQmGFuzQ',
    appId: '1:1062714679882:web:32efce660dec667ad63cb3',
    messagingSenderId: '1062714679882',
    projectId: 'chatflutter-5e756',
    authDomain: 'chatflutter-5e756.firebaseapp.com',
    storageBucket: 'chatflutter-5e756.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvGXQHkkOIhR1tLY29Wvcyg6NxCIdkBM',
    appId: '1:1062714679882:android:53dd74a860520eeed63cb3',
    messagingSenderId: '1062714679882',
    projectId: 'chatflutter-5e756',
    storageBucket: 'chatflutter-5e756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLZcnVV2TglDrtQps5YNKv8ZGscwMs-zc',
    appId: '1:1062714679882:ios:ae486f49e60180dcd63cb3',
    messagingSenderId: '1062714679882',
    projectId: 'chatflutter-5e756',
    storageBucket: 'chatflutter-5e756.appspot.com',
    androidClientId: '1062714679882-m0gt9unv1ho2ptcqbk8fnbhj5v7p986e.apps.googleusercontent.com',
    iosClientId: '1062714679882-1pjrfhgq8qqgv1av19eub982vngn24bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLZcnVV2TglDrtQps5YNKv8ZGscwMs-zc',
    appId: '1:1062714679882:ios:ae486f49e60180dcd63cb3',
    messagingSenderId: '1062714679882',
    projectId: 'chatflutter-5e756',
    storageBucket: 'chatflutter-5e756.appspot.com',
    androidClientId: '1062714679882-m0gt9unv1ho2ptcqbk8fnbhj5v7p986e.apps.googleusercontent.com',
    iosClientId: '1062714679882-1pjrfhgq8qqgv1av19eub982vngn24bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATM_PB6viTMNV_BmrwkL8p9NGvQmGFuzQ',
    appId: '1:1062714679882:web:ea11d7caf7273cfbd63cb3',
    messagingSenderId: '1062714679882',
    projectId: 'chatflutter-5e756',
    authDomain: 'chatflutter-5e756.firebaseapp.com',
    storageBucket: 'chatflutter-5e756.appspot.com',
  );
}
